version: Nightly Build {build} - AppVeyor

pull_requests:
  do_not_increment_build_number: true
  
branches:
  only:
  - main
  
max_jobs: 2

image:
- Visual Studio 2015
- macOS-BigSur
- Ubuntu

platform:
- x86

configuration:
- Release

matrix:
- fast_finish: true

artifacts:
- openspadesplus/openspades.mk/

for:
- matrix:
    only:
      - image: Ubuntu
      - build_script:
            - sh: >-
              - echo Installing dependencies...
              - sudo apt-get update
              - sudo apt-get install pkg-config
              - sudo apt-get install libglew-dev
              - sudo apt-get install libcurl3-openssl-dev
              - sudo apt-get install libsdl2-image-dev
              - sudo apt-get install libalut-dev
              - sudo apt-get install libsdl2-dev
              - sudo apt-get install xdg-utils
              - sudo apt-get install libfreetype6-dev
              - sudo apt-get install libopus-dev
              - sudo apt-get install libopusfile-dev
              - sudo apt-get install imagemagick
              - sudo apt-get install libjpeg-dev
              - sudo apt-get install libxinerama-dev
              - sudo apt-get install libxft-dev
              - echo Finished!
              - echo Building OpenSpades+
              - git clone https://github.com/nonperforming/openspadesplus
              - cd openspadesplus
              - ls
              - ./build.sh

for:
- matrix:
    only:
      - image: macOS-BigSur
      - build_script:
        - sh: >-
          - brew install pkg-config
          - git clone https://github.com/nonperforming/openspadesplus
          - cd openspadesplus
          - vcpkg/bootstrap-vcpkg.sh
          - vcpkg/vcpkg install @vcpkg_x86_64-darwin.txt
          - mkdir openspades.mk
          - cd openspades.mk
          - cmake -G Ninja .. -D CMAKE_BUILD_TYPE=RelWithDebInfo -D CMAKE_OSX_ARCHITECTURES=x86_64 -D CMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -D VCPKG_TARGET_TRIPLET=x64-osx
          - ninja

for:
- matrix:
  only:
    - image: Visual Studio 2015
    - build_script:
      - ps: >-
        - git clone https://github.com/nonperforming/openspadesplus
        - cd openspadesplus
        - vcpkg/bootstrap-vcpkg.bat
        - vcpkg/vcpkg install @vcpkg_x86-windows.txt
        - mkdir openspades.mk
        - cd openspades.mk
        - cmake -A Win32 -D CMAKE_BUILD_TYPE=RelWithDebInfo -D VCPKG_TARGET_TRIPLET=x86-windows-static
      
