name: CI/CD
on:
  pull_request:
  push:

jobs:
  build-windows:
    name: Build (Windows)
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true
          path: openspades

      - name: Cache vcpkg and dependencies
        uses: actions/cache@v2
        with:
          path: |
            vcpkg/installed
            !.git
          key: ${{ runner.os }}-${{ hashFiles('vcpkg_x86-windows.txt', '.gitmodules') }}

      - name: Bootstrap vcpkg
        run: vcpkg/bootstrap-vcpkg.bat

      - name: Build dependencies
        run: vcpkg/vcpkg install @vcpkg_x86-windows.txt

      - name: Build application
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/openspades.mk
          build-type: RelWithDebInfo
          configure-options: -A Win32 -D CMAKE_BUILD_TYPE=RelWithDebInfo -D CMAKE_TOOLCHAIN_FILE=${{ runner.workspace }}/openspades/vcpkg/scripts/buildsystems/vcpkg.cmake -D VCPKG_TARGET_TRIPLET=x86-windows-static
          parallel: 8

      - name: Archive OpenSpades+
        uses: "thedoctor0/zip-release@master"
        with:
          type: 'zip'
          filename: 'windows.zip'
          path: ${{ runner.workspace }}/openspades.mk/bin
      
      - name: "Push nightly release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly-windows"
          title: "Nightly Build - CI/CD"
          prerelease: true
          files: |
            ./windows.zip
            
  build-macos:
    name: Build (macOS)
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true
          path: openspades

      - name: Cache vcpkg and dependencies
        uses: actions/cache@v2
        with:
          path: |
            vcpkg/installed
            !.git
          key: ${{ runner.os }}-${{ hashFiles('vcpkg_x86_64-darwin.txt', '.gitmodules') }}

      - name: Bootstrap vcpkg
        run: vcpkg/bootstrap-vcpkg.sh

      - name: Build dependencies
        run: vcpkg/vcpkg install @vcpkg_x86_64-darwin.txt

      - name: Build application
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/openspades.mk
          build-type: RelWithDebInfo
          configure-options: -D CMAKE_BUILD_TYPE=RelWithDebInfo -D CMAKE_TOOLCHAIN_FILE=${{ runner.workspace }}/openspades/vcpkg/scripts/buildsystems/vcpkg.cmake -D VCPKG_TARGET_TRIPLET=x64-osx -D CMAKE_OSX_ARCHITECTURES=x86_64
          parallel: 8
          
      - name: Archive OpenSpades.app
        uses: "thedoctor0/zip-release@master"
        with:
          type: 'zip'
          filename: 'macos.zip'
          path: "/Users/runner/work/openspadesplus/openspades.mk/bin/OpenSpades.app"
      
      - name: "Push nightly release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly-macos"
          title: "Nightly Build - CI/CD"
          prerelease: true
          files: |
            ./macos.zip
            
